# -Denv=dev -Dapollo.cluster=DEFAULT -Dserver.port=53050
app:
  id: wanxin-finance-account-service
apollo:
  bootstrap:
    enabled: true
    namespaces: application,micro_service.spring-boot-http,micro_service.spring-eureka,micro_service.spring-boot-mysql,micro_service.spring-boot-druid,micro_service.mybatis-plus,micro_service.spring-cloud-hmily

spring:
  application:
    name: ${app.id}

logging:
  config: classpath:log4j2-dev.xml





