spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.142:8848
  rabbitmq:
    host: 192.168.2.142
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual