app:
  id: wanxin-finance-third-service
apollo:
  bootstrap:
    enabled: true
    namespaces: application

spring:
  application:
    name: wanxin-finance-third-service

swagger:
  enable: true

logging:
  config: classpath:log4j2.xml
    


